const ITEM = {
    WOOD: 'WOOD',
    COBBLESTONE: 'COBBLESTONE',
    REFINED_WOOD: 'REFINED_WOOD',
    WOODEN_PICKAXE: 'WOODEN_PICKAXE',
    IRON_PICKAXE: 'IRON_PICKAXE',
    STICK: 'STICK',
    IRON_INGOT: 'IRON_INGOT',
    IRON_ORE: 'IRON_ORE',
    FLINT: 'FLINT',
    FLINT_AND_STEEL: 'FLINT_AND_STEEL',
    COAL: 'COAL',
    TORCH: 'TORCH',
}

export default ITEM;