const ITEM = {
    // Basic materials
    OAK_LOG: 'OAK_LOG',
    OAK_PLANKS: 'OAK_PLANKS',
    COBBLESTONE: 'COBBLESTONE',
    IRON_INGOT: 'IRON_INGOT',
    IRON_ORE: 'IRON_ORE',
    GOLD_INGOT: 'GOLD_INGOT',
    GOLD_ORE: 'GOLD_ORE',
    DIAMOND: 'DIAMOND',
    STICK: 'STICK',
    FLINT: 'FLINT',

    // Pickaxes
    WOODEN_PICKAXE: 'WOODEN_PICKAXE',
    STONE_PICKAXE: 'STONE_PICKAXE',
    IRON_PICKAXE: 'IRON_PICKAXE',
    GOLDEN_PICKAXE: 'GOLDEN_PICKAXE',
    DIAMOND_PICKAXE: 'DIAMOND_PICKAXE',

    // Shovels
    WOODEN_SHOVEL: 'WOODEN_SHOVEL',
    STONE_SHOVEL: 'STONE_SHOVEL',
    IRON_SHOVEL: 'IRON_SHOVEL',
    GOLDEN_SHOVEL: 'GOLDEN_SHOVEL',
    DIAMOND_SHOVEL: 'DIAMOND_SHOVEL',

    // Axes
    WOODEN_AXE: 'WOODEN_AXE',
    STONE_AXE: 'STONE_AXE',
    IRON_AXE: 'IRON_AXE',
    GOLDEN_AXE: 'GOLDEN_AXE',
    DIAMOND_AXE: 'DIAMOND_AXE',

    // Hoes
    WOODEN_HOE: 'WOODEN_HOE',
    STONE_HOE: 'STONE_HOE',
    IRON_HOE: 'IRON_HOE',
    GOLDEN_HOE: 'GOLDEN_HOE',
    DIAMOND_HOE: 'DIAMOND_HOE',

    // Commom blocks
    CRAFTING_TABLE: 'CRAFTING_TABLE',
    FURNACE: 'FURNACE',

    FLINT_AND_STEEL: 'FLINT_AND_STEEL',
    COAL: 'COAL',
    TORCH: 'TORCH',
}

export default ITEM;